spring.application.name=category-thymeleaf-crud

# Cấu hình kết nối SQL Server (sửa lại tên DB, user, pass theo máy bạn)
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=CategoryDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tắt cache Thymeleaf khi dev để sửa HTML không cần restart
spring.thymeleaf.cache=false